version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    # ports:
    #   - "8000:8000"
    volumes:
      - ./code-server/.config:/home/coder/.config
      - ./code-server/settings.json:/home/coder/.local/share/code-server/User/settings.json

  # bitnami-nginx:
  #   image: bitnami/nginx:latest
  #   restart: unless-stopped
  #   # command: --with-http_sub_module
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/server-block.conf:/opt/bitnami/nginx/conf/server_blocks/server-block.conf:ro

  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # caddy:
  #   image: caddy:2-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  default:
    external: true
    name: code-server