version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - ./code-server/.config:/home/coder/.config
      - ./code-server/projects:/home/coder/projects
      - ./code-server/settings.json:/home/coder/.local/share/code-server/User/settings.json

networks:
  default:
    external: true
    name: code-server